services:
  eclipsejdtls:
    image: ghcr.io/typefox/monaco-languageclient/eclipse.jdt.ls:latest
    platform: linux/amd64
    command: [
      "bash", "-c", "npm run start:example:server:jdtls"
    ]
    ports:
      - 30003:30003
    working_dir: /home/mlc
    container_name: eclipsejdtls
    volumes:
      - /Users/dy/Workspace/flow-engine-demo:/home/mlc/packages/examples/resources/eclipse.jdt.ls/workspace